### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by spheregenomics** [fikriauliya/angularjs-rails-api-devise-bootstrap#1]
This looks like a great repo. I am unsure how to install.

So far:

```
$ git clone ....
$ bundle install
$ rake db:migrate:setup
cd client
gulp serve:full-stack

module.js:340
    throw err;
          ^
Error: Cannot find module 'require-dir'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/fluent/fluent/client/gulpfile.js:12:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by fikriauliya** [comment]
Try:
   ...
   cd client
   bower install
   gulp serve

**Comment by scarroll32** [comment]
Thank you!
